BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "summary" (
	"id"	INTEGER,
	"registers"	TEXT,
	"date_insert"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER,
	"users_id"	INTEGER,
	"users_firstName"	TEXT,
	"users_lastName"	TEXT,
	"users_maidenName"	TEXT,
	"users_age"	INTEGER,
	"users_gender"	TEXT,
	"users_email"	TEXT,
	"users_phone"	TEXT,
	"users_username"	TEXT,
	"users_password"	TEXT,
	"users_birthDate"	TEXT,
	"users_image"	TEXT,
	"users_bloodGroup"	TEXT,
	"users_height"	NUMERIC,
	"users_weight"	NUMERIC,
	"users_eyeColor"	TEXT,
	"users_hair_color"	TEXT,
	"users_hair_type"	TEXT,
	"users_ip"	TEXT,
	"users_address_address"	TEXT,
	"users_address_city"	TEXT,
	"users_address_state"	TEXT,
	"users_address_stateCode"	TEXT,
	"users_address_postalCode"	TEXT,
	"users_address_coordinates_lat"	TEXT,
	"users_address_coordinates_lng"	TEXT,
	"users_address_country"	TEXT,
	"users_macAddress"	TEXT,
	"users_university"	TEXT,
	"users_bank_cardExpire"	TEXT,
	"users_bank_cardNumber"	TEXT,
	"users_bank_cardType"	TEXT,
	"users_bank_currency"	TEXT,
	"users_bank_iban"	TEXT,
	"users_company_department"	TEXT,
	"users_company_name"	TEXT,
	"users_company_title"	TEXT,
	"users_company_address_address"	TEXT,
	"users_company_address_city"	TEXT,
	"users_company_address_state"	TEXT,
	"users_company_address_stateCode"	TEXT,
	"users_company_address_postalCode"	TEXT,
	"users_company_address_coordinates_lat"	TEXT,
	"users_company_address_coordinates_lng"	TEXT,
	"users_company_address_country"	TEXT,
	"users_ein"	TEXT,
	"users_ssn"	TEXT,
	"users_userAgent"	TEXT,
	"users_crypto_coin"	TEXT,
	"users_crypto_wallet"	TEXT,
	"users_crypto_network"	TEXT,
	"users_role"	TEXT,
	"date_insertion"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
